"""add_pedido_referencia_upsell

Revision ID: 4432e085e1dc
Revises: d12344ac7d0f
Create Date: 2025-07-02 15:42:38.763254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4432e085e1dc'
down_revision = 'd12344ac7d0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('pedido_original_id', sa.Integer(), nullable=True))
    op.add_column('pedidos', sa.Column('codigo_referencia', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'pedidos', 'pedidos', ['pedido_original_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_column('pedidos', 'codigo_referencia')
    op.drop_column('pedidos', 'pedido_original_id')
    # ### end Alembic commands ### 