"""Initial migration - create all tables

Revision ID: d12344ac7d0f
Revises: 
Create Date: 2025-07-02 11:59:21.880481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12344ac7d0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mayoristas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('gescom_db_host', sa.String(length=255), nullable=True),
    sa.Column('gescom_db_port', sa.Integer(), nullable=True),
    sa.Column('gescom_db_name', sa.String(length=255), nullable=True),
    sa.Column('gescom_db_user', sa.String(length=255), nullable=True),
    sa.Column('gescom_db_password', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_api_key', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_phone_number', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('color_secundario', sa.String(length=7), nullable=True),
    sa.Column('recomendaciones_activas', sa.Boolean(), nullable=True),
    sa.Column('tiempo_espera_horas', sa.Integer(), nullable=True),
    sa.Column('max_productos_recomendados', sa.Integer(), nullable=True),
    sa.Column('reglas_recomendacion', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mayoristas_email'), 'mayoristas', ['email'], unique=True)
    op.create_index(op.f('ix_mayoristas_id'), 'mayoristas', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gescom_cliente_id', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('mayorista_id', sa.Integer(), nullable=False),
    sa.Column('whatsapp_numero', sa.String(length=50), nullable=True),
    sa.Column('acepta_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_ultimo_pedido', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pedidos', sa.Integer(), nullable=True),
    sa.Column('ticket_promedio', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mayorista_id'], ['mayoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_gescom_cliente_id'), 'clientes', ['gescom_cliente_id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gescom_producto_id', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('mayorista_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('es_destacado', sa.Boolean(), nullable=True),
    sa.Column('orden_recomendacion', sa.Integer(), nullable=True),
    sa.Column('activo_recomendaciones', sa.Boolean(), nullable=True),
    sa.Column('veces_vendido', sa.Integer(), nullable=True),
    sa.Column('veces_recomendado', sa.Integer(), nullable=True),
    sa.Column('conversion_recomendacion', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mayorista_id'], ['mayoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=False)
    op.create_index(op.f('ix_productos_gescom_producto_id'), 'productos', ['gescom_producto_id'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('mayorista_id', sa.Integer(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mayorista_id'], ['mayoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gescom_pedido_id', sa.String(length=50), nullable=False),
    sa.Column('numero_pedido', sa.String(length=100), nullable=False),
    sa.Column('mayorista_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ORIGINAL', 'UPSELL', name='tipopedido'), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'ENVIADO', 'ENTREGADO', 'CANCELADO', name='estadopedido'), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('impuestos', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('direccion_envio', sa.Text(), nullable=True),
    sa.Column('recomendaciones_enviadas', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio_recomendaciones', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_carrito', sa.String(length=255), nullable=True),
    sa.Column('token_expiracion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('click_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('fecha_click_whatsapp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conversion_upsell', sa.Boolean(), nullable=True),
    sa.Column('monto_upsell', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha_pedido', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['mayorista_id'], ['mayoristas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_gescom_pedido_id'), 'pedidos', ['gescom_pedido_id'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_token_carrito'), 'pedidos', ['token_carrito'], unique=True)
    op.create_table('items_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descuento', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('producto_codigo', sa.String(length=100), nullable=True),
    sa.Column('producto_nombre', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_pedido_id'), 'items_pedido', ['id'], unique=False)
    op.create_table('recomendaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('mayorista_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('MAS_VENDIDOS', 'HISTORICO_CLIENTE', 'CATEGORIA_SIMILAR', 'REGLA_PERSONALIZADA', 'MANUAL', name='tiporecomendacion'), nullable=False),
    sa.Column('estado', sa.Enum('GENERADA', 'ENVIADA', 'CLICKEADA', 'CONVERTIDA', 'IGNORADA', name='estadorecomendacion'), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('razon', sa.Text(), nullable=True),
    sa.Column('producto_nombre', sa.String(length=255), nullable=True),
    sa.Column('producto_precio', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('producto_imagen_url', sa.String(length=500), nullable=True),
    sa.Column('fue_clickeada', sa.Boolean(), nullable=True),
    sa.Column('fecha_click', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fue_agregada_carrito', sa.Boolean(), nullable=True),
    sa.Column('fecha_agregada_carrito', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cantidad_agregada', sa.Integer(), nullable=True),
    sa.Column('monto_convertido', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mayorista_id'], ['mayoristas.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendaciones_id'), 'recomendaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recomendaciones_id'), table_name='recomendaciones')
    op.drop_table('recomendaciones')
    op.drop_index(op.f('ix_items_pedido_id'), table_name='items_pedido')
    op.drop_table('items_pedido')
    op.drop_index(op.f('ix_pedidos_token_carrito'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_gescom_pedido_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_gescom_producto_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_gescom_cliente_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_mayoristas_id'), table_name='mayoristas')
    op.drop_index(op.f('ix_mayoristas_email'), table_name='mayoristas')
    op.drop_table('mayoristas')
    # ### end Alembic commands ### 